# Generated by Django 4.1 on 2022-08-30 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="placed_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 8, 30, 13, 19, 25, 147572, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
