# Generated by Django 4.1 on 2022-08-30 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_book_image_alter_order_placed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="placed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
